version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  #BeforeInstall:
    #- location: codedeploy/apache_stop.sh
      #timeout: 300
      #runas: root
  ApplicationStart:
    - location: codedeploy/tempo.sh
    - location: codedeploy/link.sh
      timeout: 300
      runas: root
